import { describe, expect, it } from "vitest";
import { corpus } from "../corpus";
import type { StatusEffectType } from "../types";
import sourceSeries from "./fixtures/batodex-level-series.json";

/**
 * Value-for-value regression guard on the creature corpus (2026-10-06 round 6, research.md H11).
 *
 * WHY THIS EXISTS, stated plainly because the lesson cost two rounds: round 5's bulk level-1 fill
 * had an off-by-one row alignment bug and gave **55 of 149 species the previous species' stats**.
 * It shipped because every check applied to it was shape-shaped — "596 records exist", "596
 * cooldowns are non-null", "the level progression is monotonic". All of those pass happily while
 * every value is wrong by one row. Only a value-by-value comparison against the source finds it,
 * and the first version of this guard (a heuristic looking for runs of identical neighbouring
 * stats) did **not** work either, because a shift makes record N hold record N-1's values, so
 * consecutive records still differ from each other.
 *
 * So this compares against a committed trimmed snapshot of the authoritative per-level series
 * (`fixtures/batodex-level-series.json`, regenerated by `scripts/vendor-sprites.mjs`'s extraction
 * input). Any future bulk corpus edit that misaligns rows fails here immediately and by name.
 */

type SourceLevel = {
  level: number;
  cooldown: number | null;
  multicast: number | null;
  stats: { key: string; value: number }[];
};

const STATUS_FROM_KEY: Record<string, StatusEffectType> = {
  burn: "Burn",
  poison: "Poison",
  shock: "Shock",
  shield: "Shield",
};

const series = sourceSeries as Record<string, SourceLevel[]>;

function sourceFor(name: string, level: number): SourceLevel | undefined {
  return series[name]?.find((l) => l.level === level);
}

/**
 * Species our corpus has deliberately moved AHEAD of the committed batodex snapshot.
 *
 * The snapshot is batodex at Balance 24. On 2026-10-06 the game shipped v1.3.0, whose notes change
 * 15 creatures, and those changes were applied from the official patch notes — a primary source,
 * where the fan site is a secondary one. So a mismatch here is the corpus being CORRECT and the
 * fixture being stale, not a data error.
 *
 * Listed explicitly rather than skipping the comparison wholesale: every other species must still
 * match, and when batodex catches up this set should shrink back to empty.
 *
 * Source: https://store.steampowered.com/news/app/4557380/view/686392527015643351
 */
const PATCHED_AHEAD_OF_SNAPSHOT = new Set([
  "opalion", "petrirex", "steamscuttle", "kappow", "aviarab", "dollhime", "mallogre", "danuki",
  "sarudo", "guardiant", "noxnimbus", "lignite", "stalagrove", "aegistruct", "geminiss",
]);

describe("creature corpus matches the authoritative per-level series (research.md H11)", () => {
  it("covers every species in the source, and adds none that aren't in it", () => {
    const ours = new Set(corpus.creatures.map((c) => c.name));
    const theirs = new Set(Object.keys(series));
    expect([...theirs].filter((n) => !ours.has(n))).toEqual([]);
    expect([...ours].filter((n) => !theirs.has(n))).toEqual([]);
  });

  it("every record's cooldown matches the source for its own (species, level)", () => {
    const mismatches = corpus.creatures
      .map((c) => ({ c, source: sourceFor(c.name, c.level) }))
      .filter(({ c }) => !PATCHED_AHEAD_OF_SNAPSHOT.has(c.id))
      .filter(({ c, source }) => source && Number(c.baseCooldownSeconds) !== Number(source.cooldown))
      .map(({ c, source }) => `${c.id}@L${c.level}: ours=${c.baseCooldownSeconds} source=${source!.cooldown}`);
    expect(mismatches).toEqual([]);
  });

  it("every record's damage matches the source for its own (species, level)", () => {
    const mismatches = corpus.creatures
      .map((c) => ({ c, source: sourceFor(c.name, c.level) }))
      .filter(({ c }) => !PATCHED_AHEAD_OF_SNAPSHOT.has(c.id))
      .filter(({ c, source }) => {
        if (!source) return false;
        const sourceDamage = source.stats.find((s) => s.key === "damage");
        // `null` here means "the source publishes no damage line for this creature" -- which is
        // NOT the same as "confirmed to deal no damage" (research.md H9, still an open gap).
        return (c.baseDamage ?? null) !== (sourceDamage ? sourceDamage.value : null);
      })
      .map(({ c, source }) => {
        const sourceDamage = source!.stats.find((s) => s.key === "damage");
        return `${c.id}@L${c.level}: ours=${c.baseDamage} source=${sourceDamage ? sourceDamage.value : null}`;
      });
    expect(mismatches).toEqual([]);
  });

  it("every record's applied statuses match the source for its own (species, level)", () => {
    const mismatches: string[] = [];
    for (const creature of corpus.creatures) {
      const source = sourceFor(creature.name, creature.level);
      if (!source) continue;
      const expected = source.stats
        .filter((s) => STATUS_FROM_KEY[s.key])
        .map((s) => `${STATUS_FROM_KEY[s.key]}:${s.value}`)
        .sort();
      const actual = (creature.appliesStatus ?? []).map((s) => `${s.type}:${s.amount}`).sort();
      if (expected.join(",") !== actual.join(",")) {
        mismatches.push(`${creature.id}@L${creature.level}: ours=[${actual}] source=[${expected}]`);
      }
    }
    expect(mismatches).toEqual([]);
  });

  it("fails loudly if records are shifted by one row (the exact round-5 bug, reproduced)", () => {
    // Guards the guard: confirms the above comparisons genuinely detect a row shift, rather than
    // passing for some unrelated reason. Shifts a copy of the level-1 records by one and asserts
    // the same comparison logic reports a large number of mismatches.
    const level1 = corpus.creatures.filter((c) => c.level === 1);
    let shiftedMismatches = 0;
    for (let i = 1; i < level1.length; i++) {
      const record = level1[i]!;
      const wrongSource = sourceFor(level1[i - 1]!.name, 1);
      if (wrongSource && Number(record.baseCooldownSeconds) !== Number(wrongSource.cooldown)) {
        shiftedMismatches++;
      }
    }
    // If a one-row shift were undetectable, this would be near zero.
    expect(shiftedMismatches).toBeGreaterThan(100);
  });
});
